name: Validate Markdown

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.md"
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  checks:
    if: github.event.pull_request.draft == false
    uses: holdex/github-actions/.github/workflows/pr-checks.yml@05eefbf
    with:
      run-prettier: false
      run-markdown: true
      run-commits: true
      package-manager: bun

  check-links:
    if: github.event.pull_request.draft == false
    needs: checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check links
        uses: lycheeverse/lychee-action@v1
        with:
          args: >
            --verbose
            --no-progress
            --exclude-mail
            '**/*.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
